const data = [
  {
    id: '',
    type: 'rent',
    address: '289-2,Film Nagar, Jubilee Hills, Hyderabad',
    location: 'Hyderabad',
    image: 'https://wallpaperaccess.com/full/3060214.jpg',
    beds: 3,
    bathrooms: 2,
    square: '4x5 m2',
    price: 4500,
  },
  {
    id: '',
    type: 'rent',
    address: '23-10,Kothapet, Hyderabad',
    location: 'Hyderabad',
    image: 'https://wallpaperaccess.com/full/3434330.jpg',
    beds: 4,
    bathrooms: 3,
    square: '5x7 m2',
    price: 5300,
  },
  {
    id: '',
    type: 'sell',
    address: '980-12, Bolarum Hyderabad',
    location: 'Hyderabad',
    image:
      'https://i.pinimg.com/originals/b1/15/18/b11518ccfd6295f09f83b7d4baec7cfd.jpg',
    beds: 4,
    bathrooms: 3,
    square: '4x6 m2',
    price: 5300000,
  },
  {
    id: '',
    type: 'sell',
    address: 'Sriram Nagar colony,Kamareddy',
    location: 'Kamareddy',
    image:
      'https://st2.depositphotos.com/1041088/8016/i/950/depositphotos_80167630-stock-photo-modern-house-with-gray-exterior.jpg',
    beds: 3,
    bathrooms: 2,
    square: '5x5 m2',
    price: 830000,
  },
  {
    id: '',
    type: 'rent',
    address: 'Ashok Nagar colony,Kamareddy',
    location: 'Kamareddy',
    image: 'https://wallpapercave.com/wp/wp3604632.jpg',
    beds: 4,
    bathrooms: 3,
    square: '5x4 m2',
    price: 5000,
  },
  {
    id: '',
    type: 'sell',
    address: 'Vidya Nagar colony,Kamareddy',
    location: 'Kamareddy',
    image: 'https://i.ytimg.com/vi/jhxECt4eWcA/maxresdefault.jpg',
    beds: 6,
    bathrooms: 3,
    square: '6x6 m2',
    price: 150000,
  },
  {
    id: '',
    type: 'sell',
    address: 'Rajiv Nagar colony,Kamareddy',
    location: 'Kamareddy',
    image: 'https://i.ytimg.com/vi/knXxbZqLlgA/maxresdefault.jpg',
    beds: 5,
    bathrooms: 5,
    square: '5x4 m2',
    price: 250000,
  },
  {
    id: '',
    type: 'sell',
    address: 'Station Road,Kamareddy',
    location: 'Kamareddy',
    image:
      'https://www.veeduonline.in/wp-content/uploads/2015/11/anel-11-4-d1a.jpg',
    beds: 4,
    bathrooms: 2,
    square: '3x4 m2',
    price: 25000,
  },
]
